[package]
name = "rust_data_pipeline"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_data_pipeline"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
